### ISSUE TITLE
analysis.py の例外落ち

### ISSUE THREAD

**Issue by shinsa82** [shinsa82-sgi-2021/tackle-diva#41]
たぶん、想定している型と違うものが入ってる。
以下、デバッグメッセージを追加して試したもの:

```shell
(.venv) [13:51:56 ~/git/sgi/phase2/tackle-diva/rest/server] (dev)$ python -m diva_server.postprocess.analysis test/fixtures/diva_output-1/transaction.json 
digraph {
node[shape=plaintext];
subgraph cluster_0 {
label="{entry: {methods: [com.ibm.websphere.samples.daytrader.web.prims.PingServletWriter.init]}}"
}
subgraph cluster_1 {
label="{entry: {methods: [com.ibm.websphere.samples.daytrader.web.prims.PingServletWriter.doPost]}}"
}
subgraph cluster_2 {
label="{entry: {methods: [com.ibm.websphere.samples.daytrader.web.prims.PingServletWriter.doGet]}}"
}
subgraph cluster_3 {
label="{entry: {methods: [com.ibm.websphere.samples.daytrader.web.prims.ejb3.PingServlet2MDBQueue.init]}}"
}
subgraph cluster_4 {
label="{entry: {methods: [com.ibm.websphere.samples.daytrader.web.prims.ejb3.PingServlet2MDBQueue.doPost]}}"
}
subgraph cluster_5 {
label="{entry: {methods: [com.ibm.websphere.samples.daytrader.web.prims.ejb3.PingServlet2MDBQueue.doGet]}}"
}
subgraph cluster_6 {
label="{entry: {methods: [com.ibm.websphere.samples.daytrader.web.prims.ejb3.PingServlet2Entity.init]}}"
}
subgraph cluster_7 {
label="{entry: {methods: [com.ibm.websphere.samples.daytrader.web.prims.ejb3.PingServlet2Entity.doPost]}}"
}
subgraph cluster_8 {
label="{entry: {methods: [com.ibm.websphere.samples.daytrader.web.prims.ejb3.PingServlet2Entity.doGet]}}"
}
subgraph cluster_9 {
label="{entry: {methods: [com.ibm.websphere.samples.daytrader.web.TradeAppServlet.init]}}"
}
DEBUG:__main__:crud: sql = select * from accountprofileejb ap where ap.userid = (select profile_userid from accountejb a where a.profile_userid=?)
DEBUG:__main__:crud0: ast=
['select',
 ('*',),
 {':from': [{'ap': 'accountprofileejb'}]},
 ('ap.userid',),
 ['select',
  {'profile_userid': ('profile_userid',)},
  {':from': [{'a': 'accountejb'}]},
  ('a.profile_userid',)]]
DEBUG:__main__:crud0: ast=
('*',)
DEBUG:__main__:crud0: ast=
{':from': [{'ap': 'accountprofileejb'}]}
Traceback (most recent call last):
  File "/Users/shinsa/.anyenv/envs/pyenv/versions/3.7.11/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/shinsa/.anyenv/envs/pyenv/versions/3.7.11/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/shinsa/git/sgi/phase2/tackle-diva/rest/server/src/diva_server/postprocess/analysis.py", line 189, in <module>
    res = analyze(entry['transactions'], opts)
  File "/Users/shinsa/git/sgi/phase2/tackle-diva/rest/server/src/diva_server/postprocess/analysis.py", line 83, in analyze
    rs, ws = crud(op['sql'])
  File "/Users/shinsa/git/sgi/phase2/tackle-diva/rest/server/src/diva_server/postprocess/analysis.py", line 57, in crud
    return crud0(r[1])
  File "/Users/shinsa/git/sgi/phase2/tackle-diva/rest/server/src/diva_server/postprocess/analysis.py", line 41, in crud0
    rs, ws = crud0(child, ast[0] != 'select')
  File "/Users/shinsa/git/sgi/phase2/tackle-diva/rest/server/src/diva_server/postprocess/analysis.py", line 47, in crud0
    else t for t in ast[':from'] if not isinstance(t, tuple)]
  File "/Users/shinsa/git/sgi/phase2/tackle-diva/rest/server/src/diva_server/postprocess/analysis.py", line 47, in <listcomp>
    else t for t in ast[':from'] if not isinstance(t, tuple)]
TypeError: 'dict_values' object is not subscriptable
```

sqlparse.py を Python 3 で動かしたことによって出力が変わったか、
analysis.py がそうなっているのか、現時点では不明。

**Comment by shinsa82** [comment]
原因がわかりました。

- Python 2 では `dict.values()` は `list` を返す
- Python 3 ではそれはイテレータを返す
 
`2to3` も使って確認しました。たしかに修正候補に出てきます。
他にも修正するべき場所がありました。

**Comment by shinsa82** [comment]
`2to3` の出力はこちら:

```
(.venv) [14:19:01 ~/git/sgi/phase2/tackle-diva/rest/server] (dev)$ 2to3 src/diva_server/postprocess/analysis.py 
RefactoringTool: Skipping optional fixer: buffer
RefactoringTool: Skipping optional fixer: idioms
RefactoringTool: Skipping optional fixer: set_literal
RefactoringTool: Skipping optional fixer: ws_comma
RefactoringTool: Refactored src/diva_server/postprocess/analysis.py
--- src/diva_server/postprocess/analysis.py     (original)
+++ src/diva_server/postprocess/analysis.py     (refactored)
@@ -13,7 +13,7 @@
 from pprint import pformat
 
 try:
-    import urlparse
+    import urllib.parse
 except ImportError:
     import urllib.parse as urlparse
 #from urlparse import urlparse, parse_qs
@@ -44,7 +44,7 @@
             res[1] |= ws
         return res
     elif isinstance(ast, dict) and ':from' in ast:
-        ts = [t.values()[0] if isinstance(t, dict)
+        ts = [list(t.values())[0] if isinstance(t, dict)
               else t for t in ast[':from'] if not isinstance(t, tuple)]
         return [set(), set(ts)] if write else [set(ts), set()]
     else:
@@ -117,8 +117,8 @@
 
 def dump_dot(c, label, txs, opts):
 
-    print('subgraph cluster_%d {' % c)
-    print('label="%s"' % label)
+    print(('subgraph cluster_%d {' % c))
+    print(('label="%s"' % label))
     i = 0
     text = ''
 
@@ -134,7 +134,7 @@
                     rwsets[i] = op['rwset']
                 stack.append(None)
                 sql += ' ' + \
-                    json.dumps({'rwset': map(list, op['rwset'])}).replace(
+                    json.dumps({'rwset': list(map(list, op['rwset']))}).replace(
                         '"', '')
 
             text += '<tr><td align="text">%s<br align="left" /></td></tr>' % (
@@ -143,8 +143,8 @@
             if op['sql'] in ('COMMIT', 'ROLLBACK'):
                 stack.pop()
                 if not stack:
-                    print(
-                        'n%i_%i [label=<<table border="0">%s</table>>]' % (c, i, text))
+                    print((
+                        'n%i_%i [label=<<table border="0">%s</table>>]' % (c, i, text)))
                     i += 1
                     text = ''
 
@@ -163,7 +163,7 @@
     tranred(edges)
     for i in edges:
         for j in edges[i]:
-            print('n%d_%d -> n%d_%d' % (c, i, c, j))
+            print(('n%d_%d -> n%d_%d' % (c, i, c, j)))
 
     print('}')
 
@@ -173,7 +173,7 @@
     import yaml
     basicConfig(level=DEBUG)
     yaml.add_representer(OrderedDict, lambda dumper, data: dumper.represent_mapping(
-        'tag:yaml.org,2002:map', data.items()))
+        'tag:yaml.org,2002:map', list(data.items())))
     # yaml.add_representer(unicode, lambda dumper, data: dumper.represent_scalar(
     #     u'tag:yaml.org,2002:str', data))
 
RefactoringTool: Files that need to be modified:
RefactoringTool: src/diva_server/postprocess/analysis.py
```

**Comment by shinsa82** [comment]
両方直したら Python 2 版と同じ結果になったので OK。
たぶん PyYAML の representer 設定も要らないはず。

**Comment by shinsa82** [comment]
取り除いても OK  だった。
